const productos = [
    {
        "id": 1,
        "num": "001",
        "name": "BBS XR GLOSSY BLACK",
        "img": "https://i.ibb.co/fMk3NjP/XR0301-Glossy-Black-002.png",
        "price": "799",
        "disc": false,
         
    },
    {
        "id": 2,
        "num": "002",
        "name": "BBS XR PLATINUM SILVER",
        "img": "https://i.ibb.co/RvwF445/XR0301-Platinum-Silver-002.png",
        "price": "799",
        "disc": true,
     
    },
    {
        "id": 3,
        "num": "003",
        "name": "BBS XR SATIN BRONZE",
        "img": "https://i.ibb.co/0f0VyrQ/XR0301-Satin-Bronze-001.png",
        "price": "699",
        "disc": true,
    },
    {
        "id": 4,
        "num": "004",
        "name": "BBS TLA SATIN PLATINUM SILVER",
        "img": "https://i.ibb.co/YjYNtGW/TLA0101-Satin-Platinum-Silver-001.png",
        "price": "599",
        "disc": false,
    },
    {
        "id": 5,
        "num": "005",
        "name": "BBS TLA SATIN BLACK",
        "img": "https://i.ibb.co/XLbyrTX/TLA0101-Satin-Black-001.png",
        "price": "599",
        "disc": true,
    },
    {
        "id": 6,
        "num": "006",
        "name": "BBS TLA GLOSSY BRONZE",
        "img": "https://i.ibb.co/QDPgqT9/TLA0101-Glossy-Bronze-001.png",
        "price": "499",
        "disc": true,
    },
    {
        "id": 7,
        "num": "007",
        "name": "BBS SX PLATINUM SILVER ",
        "img": "https://i.ibb.co/xMVPk20/SX0604-Platinum-Silver-Diamond-Cut-004.png",
        "price": "799",
        "disc": false,
    },
    {
        "id": 8,
        "num": "008",
        "name": "BBS SX CRISTAL BLACK",
        "img": "https://i.ibb.co/VgTpxr9/SX0604-Cristal-Black-004.png",
        "price": "799",
        "disc": true,
    },
    {
        "id": 9,
        "num": "009",
        "name": "BBS SX BRILLIANT SILVER",
        "img": "https://i.ibb.co/8zmQb57/SX0604-Brilliant-Silver-004.png",
        "price": "799",
        "disc": false,
    },
    {
        "id": 10,
        "num": "010",
        "name": "BBS LM GOLD",
        "img": "https://i.ibb.co/4S2f4XD/LM273-Gold-003.png",
        "price": "799",
        "disc": false,
    },
    {
        "id": 11,
        "num": "011",
        "name": "BBS LM BRILLIANT SILVER",
        "img": "https://i.ibb.co/0MvYpVc/LM273-Briliant-Silver-003.png",
        "price": "799",
        "disc": false,
    },
    {
        "id": 12,
        "num": "012",
        "name": "BBS LM DIAMOND BLACK",
        "img": "https://i.ibb.co/xLqzr2q/LM273-Diamond-Black-003.png",
        "price": "899",
        "disc": true,
    },
    {
        "id": 13,
        "num": "013",
        "name": "BBS FI SATIN BRONZE",
        "img": "https://i.ibb.co/0ybxGSq/FI-R163-Satin-Bronze-001.png",
        "price": "999",
        "disc": false,
    },
    {
        "id": 14,
        "num": "014",
        "name": "BBS FI SATIN BLACK",
        "img": "https://i.ibb.co/JqqZhZ9/FI-R163-Satin-Black-001.png",
        "price": "1099",
        "disc": false,
    },
    {
        "id": 15,
        "num": "015",
        "name": "BBS FI PLATINUM SILVER",
        "img": "https://i.ibb.co/nwYZpQ4/FI-R163-Platinum-Silver-001.png",
        "price": "1199",
        "disc": true,
    },
]

